### ISSUE TITLE
(png) alpha gradient possible?

### ISSUE THREAD

**Issue by frostworx** [texus/TransparentWindows#1]
hi!
great example!
currently I consider to enhance my old (linux) game launcher
https://github.com/frostworx/typhon-launcher
a bit and would like to make it work optionally as some "desktop HUD overlay",
so you could work on both the launcher and on the desktop, depending on where you click etc.
for that I need alpha gradient compatibility, but I haven't found a way to make it work.
all alpha gradients are cut rough, so either it is transparent or black.
(f.e. with that image: https://github.com/frostworx/typhon-launcher/blob/master/data/themedata/typhon/jewelcase1.png  )
do you have a clue if that could work correctly?
would be nice if you could help.
In case I get something to work, would you mind me committing your code in my project?
of course with mentioning the source.

**Comment by texus** [comment]
Hi,

I'm afraid I can't immediately help you with that, I'm not even certain 
if it is possible. My code uses a method that sets the opacity of the 
entire window, I don't know if you can set a different opacity for each 
pixel somehow.

I've done a quick search and although I find some references to X 
Trancluent Windows I can't find any examples or documentation for them, 
so I can't find out if they would be capable of doing such thing. Plus 
I'm not that familiar with X11.

It would be cool if it were possible though, I would even be willing to 
spend some time trying to get it to work if I knew for sure that it 
could be done and have some idea where to start. If you would be able to 
show code that does it on windows and it runs with wine then I would 
even be willing to dive in the source code of wine again to find out 
what functions they use.

If any of my code is useful to you then you can freely use it. I noticed 
that I forgot to add a license to the project but everything that I put 
on github can be considered under the zlib/libpng license.

Bruno

**Comment by frostworx** [comment]
hello Bruno,
thank you very much for your friendly, quick and long reply!
Now I know that I haven't missed something obvious ;)
In case I find something useful I will let you know for sure.
thank you for your kind offer and thanks a lot for freeing your sourcecode!
friendly,
Marcel
