### ISSUE TITLE
mac osx ei capitan render black background

### ISSUE THREAD

**Issue by defims** [texus/TransparentWindows#2]
i feel confuse about the code you write about macos

``` cpp
#elif defined (SFML_SYSTEM_MACOS)
    bool setShape(sf::WindowHandle handle, const sf::Image& image);
    bool setTransparency(sf::WindowHandle handle, unsigned char alpha);
#else
```

when those two function be call, nothing happen.And I run the code in mac, a borderless window with black background and an image in it appear like this:
![2015-12-12 16 16 50](https://cloud.githubusercontent.com/assets/767580/11760975/e65f3df4-a0eb-11e5-90a8-e66dd7d4f72a.png)

**Comment by defims** [comment]
I forget to add Transparent.mm file,after I add Transparent.mm, It work correct.

**Comment by texus** [comment]
I'm surprised to see that it actually ran without the Transparent.mm file, I would have expected it to give linking errors if the file was missing.
